spring: 
  datasource: 
    url : jdbc:mysql:///hotel
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
#     ddl-auto : create
    properties:
      dialect : org.hibernate.dialect.MySQL5Dialect 